name: qa
on:
  schedule:
    - cron:  '0 3 * * 0'
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  integration-tests:
    uses: ivy-llc/ivy-integration-tests/.github/workflows/qa-integration-tests.yml@main
    secrets: inherit
