name: Release Workflow
on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  deploy:
    name: Deploy to PyPI
    uses: ./.github/workflows/pypi.yml
    secrets: inherit
